# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fOr0uLPs6-q7r3ijXYguf_3FeyeHesMG
"""

import pandas as pd

df=pd.read_csv('https://raw.githubusercontent.com/nayanbanarase/salary_predictor/refs/heads/main/Salary_Data.csv')

df.head()

df.isnull().sum()

for col in ['Age', 'Years of Experience', 'Salary']:
    if df[col].isnull().any():
        df[col].fillna(df[col].mean(), inplace=True)

for col in ['Gender', 'Education Level', 'Job Title']:
    if df[col].isnull().any():
        df[col].fillna(df[col].mode()[0], inplace=True)

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

# Identify categorical columns (excluding 'Age', 'Years of Experience', 'Salary' which are numerical)
categorical_cols = ['Gender', 'Education Level', 'Job Title']

for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

display(df.head())

df.duplicated()

# Separate features (X) and target (y)
X = df.drop('Salary', axis=1)
y = df['Salary']

print('Shape of X:', X.shape)
print('Shape of y:', y.shape)

display(X.head())
display(y.head())

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print('Shape of X_train:', X_train.shape)
print('Shape of X_test:', X_test.shape)
print('Shape of y_train:', y_train.shape)
print('Shape of y_test:', y_test.shape)

# Initialize and train the Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

print("Model training complete.")

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse**0.5 # Root Mean Squared Error
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

"""### K-Nearest Neighbors (KNN) Regressor"""

from sklearn.neighbors import KNeighborsRegressor

knn_model = KNeighborsRegressor()
knn_model.fit(X_train, y_train)

y_pred_knn = knn_model.predict(X_test)

mae_knn = mean_absolute_error(y_test, y_pred_knn)
mse_knn = mean_squared_error(y_test, y_pred_knn)
rmse_knn = mse_knn**0.5
r2_knn = r2_score(y_test, y_pred_knn)

print(f"--- KNN Regressor Performance ---")
print(f"Mean Absolute Error (MAE): {mae_knn:.2f}")
print(f"Mean Squared Error (MSE): {mse_knn:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_knn:.2f}")
print(f"R-squared (R2): {r2_knn:.2f}")

"""### Support Vector Machine (SVM) Regressor"""

from sklearn.svm import SVR

svm_model = SVR()
svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

mae_svm = mean_absolute_error(y_test, y_pred_svm)
mse_svm = mean_squared_error(y_test, y_pred_svm)
rmse_svm = mse_svm**0.5
r2_svm = r2_score(y_test, y_pred_svm)

print(f"--- SVR Performance ---")
print(f"Mean Absolute Error (MAE): {mae_svm:.2f}")
print(f"Mean Squared Error (MSE): {mse_svm:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_svm:.2f}")
print(f"R-squared (R2): {r2_svm:.2f}")

"""### Decision Tree Regressor"""

from sklearn.tree import DecisionTreeRegressor

dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

mae_dt = mean_absolute_error(y_test, y_pred_dt)
mse_dt = mean_squared_error(y_test, y_pred_dt)
rmse_dt = mse_dt**0.5
r2_dt = r2_score(y_test, y_pred_dt)

print(f"--- Decision Tree Regressor Performance ---")
print(f"Mean Absolute Error (MAE): {mae_dt:.2f}")
print(f"Mean Squared Error (MSE): {mse_dt:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_dt:.2f}")
print(f"R-squared (R2): {r2_dt:.2f}")

"""### Random Forest Regressor"""

from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)
rmse_rf = mse_rf**0.5
r2_rf = r2_score(y_test, y_pred_rf)

print(f"--- Random Forest Regressor Performance ---")
print(f"Mean Absolute Error (MAE): {mae_rf:.2f}")
print(f"Mean Squared Error (MSE): {mse_rf:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_rf:.2f}")
print(f"R-squared (R2): {r2_rf:.2f}")

"""### Naive Bayes

Naive Bayes classifiers are probabilistic machine learning models primarily used for classification tasks. Since 'Salary' is a continuous numerical target variable, this is a regression problem, and standard Naive Bayes models (like Gaussian Naive Bayes, Multinomial Naive Bayes) are not directly applicable. You would typically need to discretize the target variable to use Naive Bayes, which can complicate the interpretation of the results for a regression problem.

### Summary of Model Performance
"""

results = pd.DataFrame({
    'Model': ['Linear Regression', 'KNN Regressor', 'SVR', 'Decision Tree Regressor', 'Random Forest Regressor'],
    'MAE': [mae, mae_knn, mae_svm, mae_dt, mae_rf],
    'MSE': [mse, mse_knn, mse_svm, mse_dt, mse_rf],
    'RMSE': [rmse, rmse_knn, rmse_svm, rmse_dt, rmse_rf],
    'R2': [r2, r2_knn, r2_svm, r2_dt, r2_rf]
})

display(results.sort_values(by='R2', ascending=False))

import matplotlib.pyplot as plt
import seaborn as sns

# Set style for plots
sns.set_style('whitegrid')

# Create subplots for each metric
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Model Performance Comparison', fontsize=18)

# Plot R2 Score
sns.barplot(ax=axes[0, 0], x='Model', y='R2', data=results.sort_values(by='R2', ascending=False), palette='viridis', hue='Model', legend=False)
axes[0, 0].set_title('R-squared (R2) Score')
axes[0, 0].set_ylabel('R2 Score')
axes[0, 0].tick_params(axis='x', rotation=45)

# Plot Mean Absolute Error (MAE)
sns.barplot(ax=axes[0, 1], x='Model', y='MAE', data=results.sort_values(by='MAE', ascending=True), palette='magma', hue='Model', legend=False)
axes[0, 1].set_title('Mean Absolute Error (MAE)')
axes[0, 1].set_ylabel('MAE')
axes[0, 1].tick_params(axis='x', rotation=45)

# Plot Mean Squared Error (MSE)
sns.barplot(ax=axes[1, 0], x='Model', y='MSE', data=results.sort_values(by='MSE', ascending=True), palette='cividis', hue='Model', legend=False)
axes[1, 0].set_title('Mean Squared Error (MSE)')
axes[1, 0].set_ylabel('MSE')
axes[1, 0].tick_params(axis='x', rotation=45)

# Plot Root Mean Squared Error (RMSE)
sns.barplot(ax=axes[1, 1], x='Model', y='RMSE', data=results.sort_values(by='RMSE', ascending=True), palette='plasma', hue='Model', legend=False)
axes[1, 1].set_title('Root Mean Squared Error (RMSE)')
axes[1, 1].set_ylabel('RMSE')
axes[1, 1].tick_params(axis='x', rotation=45)

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

import pickle

# Assuming rf_model is your best model (Random Forest Regressor)
model_filename = 'random_forest_regressor_model.pkl'

# Save the model to a .pkl file
with open(model_filename, 'wb') as file:
    pickle.dump(rf_model, file)

print(f"Best model (Random Forest Regressor) saved to {model_filename}")

"""You can download the saved model file using the following code:"""

from google.colab import files

files.download(model_filename)

